ci cd file name clash

diff --git a/.github/workflows/dev-cicd.yml b/.github/workflows/dev-cicd.yml
--- a/.github/workflows/dev-cicd.yml
+++ b/.github/workflows/dev-cicd.yml
@@ -87,7 +87,7 @@ jobs:
         if: matrix.python3-version == '12'
         uses: actions/upload-artifact@v4
         with:
-          name: test-py312-status
+          name: test-py312-status-${{ matrix.os }}
           path: test-py312-status.txt
       
       - name: Check Python 3.12 Test Results
@@ -186,7 +186,7 @@ jobs:
         if: matrix.python3-version == '12'
         uses: actions/upload-artifact@v4
         with:
-          name: build-py312-status
+          name: build-py312-status-${{ matrix.os }}
           path: build-py312-status.txt
       - name: Check Python 3.12 Test Results
         if: matrix.python3-version == '12' && failure()
@@ -271,27 +271,67 @@ jobs:
             dist/windows/HeLab-windows.zip
             dist/ubuntu/HeLab-ubuntu.zip
 
-      - name: Download Test Status Artifact
+      - name: Download Test Status Artifacts
         uses: actions/download-artifact@v4
         with:
-          name: test-py312-status
-          path: test_status
-
-      - name: Download Build Status Artifact
+          name: test-py312-status-macos
+          path: .
+      - name: Download Test Status Artifacts
         uses: actions/download-artifact@v4
         with:
-          name: build-py312-status
-          path: test_status
+          name: test-py312-status-windows
+          path: .
+      - name: Download Test Status Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: test-py312-status-ubuntu
+          path: .
+      
+      - name: Download Build Status Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: build-py312-status-macos
+          path: .
+      - name: Download Build Status Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: build-py312-status-windows
+          path: .
+      - name: Download Build Status Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: build-py312-status-ubuntu
+          path: .
 
-      - name: Check Test and Build Status
+      - name: Check Test and Build Status for macOS
         run: |
-          TEST_STATUS=$(cat test-py312-status.txt)
-          BUILD_STATUS=$(cat build-py312-status.txt)
-          echo "Test status: $TEST_STATUS"
-          echo "Build status: $BUILD_STATUS"
+          TEST_STATUS=$(cat test-py312-status-macos.txt)
+          BUILD_STATUS=$(cat build-py312-status-macos.txt)
+          echo "macOS Test status: $TEST_STATUS"
+          echo "macOS Build status: $BUILD_STATUS"
           if [ "$TEST_STATUS" != "success" ] || [ "$BUILD_STATUS" != "success" ]; then
-            echo "Python 3.12 test or build failed. Failing workflow."
+            echo "Python 3.12 macOS test or build failed. Failing workflow."
             exit 1
           fi
-        shell: bash
 
+      - name: Check Test and Build Status for Windows
+        run: |
+          TEST_STATUS=$(cat test-py312-status-windows.txt)
+          BUILD_STATUS=$(cat build-py312-status-windows.txt)
+          echo "Windows Test status: $TEST_STATUS"
+          echo "Windows Build status: $BUILD_STATUS"
+          if [ "$TEST_STATUS" != "success" ] || [ "$BUILD_STATUS" != "success" ]; then
+            echo "Python 3.12 Windows test or build failed. Failing workflow."
+            exit 1
+          fi
+
+      - name: Check Test and Build Status for Ubuntu
+        run: |
+          TEST_STATUS=$(cat test-py312-status-ubuntu.txt)
+          BUILD_STATUS=$(cat build-py312-status-ubuntu.txt)
+          echo "Ubuntu Test status: $TEST_STATUS"
+          echo "Ubuntu Build status: $BUILD_STATUS"
+          if [ "$TEST_STATUS" != "success" ] || [ "$BUILD_STATUS" != "success" ]; then
+            echo "Python 3.12 Ubuntu test or build failed. Failing workflow."
+            exit 1
+          fi
